apiVersion: cluster.x-k8s.io/v1beta2
kind: Cluster
metadata:
  name: production-cluster-01
spec:
  topology:
    classRef:
      name: dev-cluster-class
    version: v1.31.0
    controlPlane:
      replicas: 1
    workers:
      machineDeployments:
        - class: dev-worker
          name: primary-workers
          replicas: 2