apiVersion: cluster.x-k8s.io/v1beta2
kind: ClusterClass
metadata:
  name: dev-cluster-class
spec:
  infrastructure:
    templateRef:
      apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
      kind: DevClusterTemplate
      name: dev-cluster-template
  controlPlane:
    templateRef:
      apiVersion: controlplane.cluster.x-k8s.io/v1beta2
      kind: KubeadmControlPlaneTemplate
      name: dev-controlplane-config
    machineInfrastructure:
      templateRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
        kind: DevMachineTemplate
        name: dev-machine-template
  workers:
    machineDeployments:
      - class: linux-workers
        template:
          bootstrap:
            templateRef:
              apiVersion: bootstrap.cluster.x-k8s.io/v1beta2
              kind: KubeadmConfigTemplate
              name: dev-worker-config
          infrastructure:
            templateRef:
              apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
              kind: DevMachineTemplate
              name: dev-machine-template