apiVersion: controlplane.cluster.x-k8s.io/v1beta2
kind: KubeadmControlPlaneTemplate
metadata:
  name: dev-controlplane-config
spec:
  template:
    spec:
      kubeadmConfigSpec:
        initConfiguration:
          nodeRegistration:
            criSocket: /var/run/containerd/containerd.sock
        joinConfiguration:
          nodeRegistration:
            criSocket: /var/run/containerd/containerd.sock