name: Test

on:
  push:
    branches: [ "main" ]

jobs:
  create-cluster:
    runs-on: ubuntu-latest
    steps:
      - name: Create cluster
        uses: helm/kind-action@v1

      - name: Apply resources
        run: |
          kustomize build ./resources | kubectl apply -f -

      - name: Wait for cluster being ready
        run: |
          echo "Waiting for cluster control plane to report Provisioned status..."
          kubectl wait --for=condition=Ready cluster/production-cluster-01 --timeout=2m
          
          echo "Waiting for Kubeadm control plane to be initialized..."
          kubectl wait --for=jsonpath='{.status.initialized}'=true kubeadmcontrolplane/production-cluster-01-control-plane --timeout=2m